# Generated by Django 4.0.3 on 2022-11-08 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numbo', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='nonvoter',
            field=models.ManyToManyField(related_name='nonvoter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='nonvoter',
            field=models.ManyToManyField(related_name='nonvoter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
